### ISSUE TITLE
Make UI more user friendly with labels and descriptions

### ISSUE THREAD

**Issue by dartar** [johnsamuelwrites/wdprop#1]
Right now the interface feels very dry. Adding localized labels and descriptions for properties, and maybe even usage examples would make the reports much more usable.

**Comment by johnsamuelwrites** [comment]
I agree. UI needs a major overhaul. With key features now ready, I now want to focus on the user interface, keeping in mind the multilingual nature of Wikidata. So localized labels and descriptions will be added instead of just the property numbers.

**Comment by johnsamuelwrites** [comment]
The latest release [v0.11](https://github.com/johnsamuelwrites/wdprop/releases/tag/v0.11) is now responsive and also gives examples, with about sections, links to articles etc.
