### ISSUE TITLE
Property information

### ISSUE THREAD

**Issue by johnsamuelwrites** [johnsamuelwrites/wdprop#6]
Show additional information on property page
* property creation date
* property data type

**Comment by VladimirAlexiev** [comment]
@johnsamuelwrites I think you should add a lot more info.
* When I look at https://wdprop.toolforge.org/property.html?property=P123, I see only translation info.
  How would I know whether that prop is interesting for me, and whether I should even open the page?
* Compare to https://sqid.toolforge.org/#/view?id=P123&lang=en

I think you have a lot more useful classifications than SQID, but the info that you display is much poorer.
* So currently your tool is not "Everything about Wikidata properties"
* but is "Everything about **translation of** Wikidata properties"

Cheers!

**Comment by johnsamuelwrites** [comment]
@VladimirAlexiev Thank you for the feedback. I agree that a lot more information about Wikidata properties could be added and the display interface could be further improved. I am tracking some desired features/information in [TODO.md](https://github.com/johnsamuelwrites/wdprop/blob/master/TODO.md). Please let me know what other information you would like to see. 

Unlike SQID, WDProp is based on obtaining real-time information from Wikidata using SPARQL queries. It was a design decision, taken particularly to focus on granular level of analysis. Some interesting statistics cannot be easily added because of technical limitations like query timeouts (e.g., usage count of properties etc.)

Over the years, I started focusing on the property translations. Hence, the property page highlights more on translation status, [translation path](https://wdprop.toolforge.org/path.html?property=P123) or [its visualization](https://wdprop.toolforge.org/pathviz.html?property=P123). (I like your observation  "Everything about **translation of** Wikidata properties" :) )

But WDProp also gives information on Wikiprojects, data types, provenance information etc. I now feel that these could also be added/linked to the property page. I will add them in the upcoming release. 

Thanks once again and please do not hesitate to create issues/submit PR. 

Best Regards,
John Samuel

**Comment by johnsamuelwrites** [comment]
Updated interface with more information related to properties

![image](https://user-images.githubusercontent.com/8275121/145807050-8783c93a-5a23-4fda-87d0-fdcb73ead372.png)
